conformance_automated = "Fail"
errors_diff = """
Line 46: Expected 1 errors
Line 51: Expected 1 errors
Line 58: Expected 1 errors
Line 63: Expected 1 errors
Line 101: Expected 1 errors
Line 102: Expected 1 errors
Line 103: Expected 1 errors
Line 111: Expected 1 errors
Line 122: Expected 1 errors
Line 134: Expected 1 errors
Line 24: Unexpected errors ['callables_kwargs.py:24:5: error[type-assertion-failure] Argument does not have asserted type `int`']
Line 32: Unexpected errors ['callables_kwargs.py:32:9: error[type-assertion-failure] Argument does not have asserted type `str`']
Line 35: Unexpected errors ['callables_kwargs.py:35:5: error[type-assertion-failure] Argument does not have asserted type `str`']
Line 41: Unexpected errors ['callables_kwargs.py:41:5: error[type-assertion-failure] Argument does not have asserted type `TD1`']
Line 62: Unexpected errors ['callables_kwargs.py:62:5: error[missing-argument] No argument provided for required parameter `v3` of function `func2`']
"""
output = """
callables_kwargs.py:24:5: error[type-assertion-failure] Argument does not have asserted type `int`
callables_kwargs.py:32:9: error[type-assertion-failure] Argument does not have asserted type `str`
callables_kwargs.py:35:5: error[type-assertion-failure] Argument does not have asserted type `str`
callables_kwargs.py:41:5: error[type-assertion-failure] Argument does not have asserted type `TD1`
callables_kwargs.py:52:11: error[too-many-positional-arguments] Too many positional arguments to function `func1`: expected 0, got 3
callables_kwargs.py:62:5: error[missing-argument] No argument provided for required parameter `v3` of function `func2`
callables_kwargs.py:64:11: error[invalid-argument-type] Argument to function `func2` is incorrect: Expected `str`, found `Literal[1]`
callables_kwargs.py:65:5: error[missing-argument] No argument provided for required parameter `v3` of function `func2`
"""
