conformance_automated = "Fail"
errors_diff = """
Line 26: Expected 1 errors
Line 38: Expected 1 errors
Line 53: Unexpected errors ['historical_positional.py:53: error: Unexpected keyword argument "__y" for "f4"  [call-arg]']
"""
output = """
historical_positional.py:18: error: Unexpected keyword argument "__x" for "f1"  [call-arg]
historical_positional.py:43: error: Unexpected keyword argument "__x" for "m1" of "A"  [call-arg]
historical_positional.py:53: error: Unexpected keyword argument "__y" for "f4"  [call-arg]
"""
